#!/bin/sh

# Check that indent is installed
command -v indent >/dev/null 2>&1 || { echo >&2 "I require 'indent' but it is not installed. Aborting."; exit 1; }

# Format code to GNU
#find ./ -type f -name '*.[ch]' -exec indent '{}' \;
# Format
find ./ -type f -name '*.[ch]' -exec indent '{}' -kr -ci4 -cli4 -i4 -l79 -nut \;
