.TH EDCOUNT "1" "December 2018" "edcount 1.0.0" "User Commands"
.SH NAME
edcount - Estimate distinct count
.SH SYNOPSIS
.B edcount [
.I OPTION
]...
.SH DESCRIPTION
Estimate distinct count of values from standard input.
Value is considered terminated with a newline.
.SH OPTIONS
.B -h, --help
.RS
Print this help message.
.RE
.TP
.B --version
.RS
Print version and copyright information.
.RE
.TP
.B -v, --verbose
.RS
Print additional information about the data.
Error bounds, number of input records, etc.
.RE
.SH BUGS
Report bugs to: <haroldfreeman@protonmail.com>
.br
Package home page: <https://github.com/haroldfreeman/edcount>
.SH COPYRIGHT
Copyright \(co 2018 Harold Freeman
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
